---
- include: k8s-certificates/main.yml

- include_role:
    name: coreos
    tasks_from: gather_facts
  vars:
    cenv: {}
    config:
      write_files:
      - path: /etc/kubernetes/ssl/ca.pem
        content: "{{ kube_ca }}"

      - path: /etc/kubernetes/ssl/worker.pem
        content: "{{ kube_worker_pem }}"

      - path: /etc/kubernetes/ssl/worker-key.pem
        content: "{{ kube_worker_key }}"

- include_role:
    name: coreos
    tasks_from: gather_facts
  vars:
    cenv: {}
    config:
      write_files:
      - path: /etc/kubernetes/ssl/ca-key.pem
        content: "{{ kube_ca_key }}"

      - path: /etc/conf.d/nfs
        permissions: '0644'
        content: |
          OPTS_RPC_MOUNTD=""

      - path: /etc/kubernetes/ssl/apiserver.pem
        content: "{{ kube_apiserver_pem }}"

      - path: /etc/kubernetes/ssl/apiserver-key.pem
        content: "{{ kube_apiserver_key }}"
  when: "'kubernetes-master' in group_names"
