---
- include_role:
    name: coreos
    tasks_from: gather_facts
  vars:
    config:
      coreos:
        units:
        - name: kube-proxy.service
          enable: true
          command: start
          content: "{{ lookup('template', 'templates/kube-proxy.service.j2') }}"
      write_files:
      - path: /etc/kube_apiserver_haproxy.cfg