kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: youtrack-{{ youtrack_name }}-pvc
  namespace: youtrack
  annotations:
    volume.beta.kubernetes.io/storage-class: "rook-block"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250M
