---
kind: Secret
apiVersion: v1
metadata:
  name: mattermost.env
  namespace: mattermost
type: Opaque
data:
  # db
  db-host: ZGI=
  # 5432
  db-port: NTQzMg==
  # mmuser
  mm-username: bW11c2Vy
  # mmuser_password
  mm-password: bW11c2VyX3Bhc3N3b3Jk
  # mattermost
  mm-dbname: bWF0dGVybW9zdA==

