---
kind: Service
apiVersion: v1
metadata:
  name: heketi
  namespace: gluster
  labels:
    glusterfs: heketi-service
  annotations:
    description: Exposes Heketi Service
spec:
  selector:
    glusterfs: heketi-pod
  ports:
  - name: heketi
    port: 8080
    targetPort: 8080
