---

- name: check kubectl
  stat:
    path: '{{ kubectl_path }}'
  register: kubectlst

- name: ensure directory
  file:
    path: '{{ kubectl_path|dirname }}'
    state: directory

- name: kubectl checksum
  local_action:
     module: shell
     args: "sha256sum {{ kubectl_path }}  | awk '{ print $1 }'"
  run_once: yes
  register: current_kubectl_checksum
  changed_when: false
  when: kubectlst.stat.exists

- name: download kubectl
  local_action:
     module: get_url
     url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/linux/amd64/kubectl"
     dest: ~/bin/
     sha256sum: "{{ kubectl_checksum }}"
     mode: 0770
  run_once: yes
  when:
  - not kubectlst.stat.exists or current_kubectl_checksum.changed
  - not current_kubectl_checksum.changed or kubectl_checksum != current_kubectl_checksum.stdout
