---
- name: Gather facts
  include: gather_facts.yml
  config:
    coreos:
      units:
      - name: 00-wired.network
        runtime: true
        content: "{{ lookup('template', 'templates/units/00-wired.network.j2') }}"

      - name: setup-network-environment.service
        command: start
        content: "{{ lookup('template', 'templates/units/setup-network-environment.service.j2') }}"
    write_files:
    - path: /opt/bin/update-window.sh
      permissions: '0755'
      owner: root
      content: "{{ lookup('template', 'templates/write_files/update-window.sh.j2') }}"

    - path: /opt/bin/update_needed.sh
      permissions: '0755'
      owner: root
      content: |
        #!/bin/bash
        . /etc/environment
        etcdctl set /needsreboot/$( cat /etc/machine-id) $( cat /etc/machine-id)
  cenv:
    coreos_public_ipv4: "{{ inventory_hostname }}"
    coreos_private_ipv4: "{{ inventory_hostname }}"

- name: Gather children facts
  include: '{{ item }}'
  with_fileglob: 'facts_gathered/*.yml'
