apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: mattermost
  labels:
    name: db
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
  selector:
    name: postgres
    namespace: mattermost

