apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mattermost-app
  namespace: mattermost
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mattermost-app
        namespace: mattermost
    spec:
      containers:
      - name: mattermost-app
        image: "mattermost/mattermost-prod-app:3.8.1"
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mattermost.env
              key: db-host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: mattermost.env
              key: db-port
        - name: MM_USERNAME
          valueFrom:
            secretKeyRef:
              name: mattermost.env
              key: mm-username
        - name: MM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mattermost.env
              key: mm-password
        - name: MM_DBNAME
          valueFrom:
            secretKeyRef:
              name: mattermost.env
              key: mm-dbname
        volumeMounts:
        - name: appdata
          mountPath: /mattermost/data
        - name: etclocaltime
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: appdata
        hostPath:
          path: /data/mm/app
      - name: etclocaltime
        hostPath:
          path: /etc/localtime
