---
- name: Machine is rebooted safely (requires hosts variable to be set)
  hosts: "{{ hosts }}"
  become: true
  tasks:
  - shell: sleep 2 && locksmithctl reboot
    async: true
    poll: false
    ignore_errors: true
  - name: Wait for server startup
    local_action:
      module: wait_for
        host={{inventory_hostname}}
        port=22
        timeout=600 delay=30
    become: false
  - name: Try to unlock
    shell: while locksmithctl unlock; do sleep 10; done