---
- name: Updates CoreOS cloud-config
  hosts: coreos
  become: true
  serial: 1
  roles:
  - role: coreos
    state: updated
  tasks:
  - name: Wait for node to come back
    local_action: wait_for host={{ inventory_hostname }} timeout=120
