---
- name: Updates CoreOS cloud-config
  hosts: coreos
  serial: 1
  roles:
  - role: coreos
    become: true
    state: updated
  tasks:
  - name: Wait for node to come back
    local_action: wait_for host={{ inventory_hostname }}
