---
- name: Cloud config is updated
  copy:
    src: "{{ coreos_config_compiled }}"
    dest: /var/lib/coreos-vagrant/vagrantfile-user-data
    force: true
- name: Safe restart
  shell: sleep 2 && locksmithctl reboot
  async: true
  poll: false
  ignore_errors: true
- name: Wait for server startup
  local_action:
    module: wait_for
      host={{inventory_hostname}}
      port=22
      timeout=900 delay=30
  become: false
- name: Try to unlock
  shell: while locksmithctl unlock; do sleep 10; done

