---
- name: Cloud config is updated
  copy:
    src: "{{ coreos_config_compiled }}"
    dest: /var/lib/coreos-vagrant/vagrantfile-user-data

- name: Restart the host
  shell: sleep 5; /sbin/shutdown -r now "cloud-config changed"
  async: 120
  poll: 0
