---
- include_role:
    name: coreos
    tasks_from: gather_facts
  vars:
    cenv: {}
    config:
      coreos:
        units:
        - name: tinc-env.service
          enable: true
          command: start
          content: "{{ lookup('template', 'templates/tinc-env.service.j2') }}"

        - name: flannel-wait.service
          command: start
          enable: true
          content: "{{ lookup('template', 'templates/flannel-wait.service.j2') }}"

        - name: tinc-conf.service
          enable: true
          command: start
          content: "{{ lookup('template', 'templates/tinc-conf.service.j2') }}"

        - name: tinc.service
          command: start
          enable: true
          content: "{{ lookup('template', 'templates/tinc.service.j2') }}"

        - name: tinc-sidekick.service
          command: start
          enable: true
          content: "{{ lookup('template', 'templates/tinc-sidekick.service.j2') }}"

        - name: docker-bridge.service
          command: start
          enable: true
          content: "{{ lookup('template', 'templates/docker-bridge.service.j2') }}"

      write_files:
      - path: /srv/tinc/tinc-up
        permissions: '0775'
        content: |
          #!/bin/sh
          brctl addif docker0 tap0 || true

      - path: /srv/tinc_initial_config.sh
        permissions: '0774'
        owner: root
        content: "{{ lookup('template', 'templates/tinc_initial_config.sh.j2') }}"

      - path: /srv/tinc_conf_updater.sh
        permissions: '0774'
        owner: root
        content: "{{ lookup('template', 'templates/tinc_conf_updater.sh.j2') }}"
