---
- name: Writes cloud-config for a K8s cluster
  hosts: coreos
  gather_facts: false
  roles:
  - role: coreos
    state: facts_gathered

  - role: coreos-etcd
    state: facts_gathered

  - role: coreos-flannel
    state: facts_gathered

  - role: coreos-tinc
    state: facts_gathered

  - role: coreos-k8s
    state: facts_gathered

  - role: coreos
    state: cloud-config
    delegate_to: localhost
    when: "'vagrant' in group_names"

#- role: coreos
#  state: ignition-config
#  delegate_to: local_host
#  when: "'vagrant' not in group_names"
#
