---
- name: Initialize Kubernetes
  hosts: kubernetes-master
  connection: local
  roles:
  - role: k8s-dns-addon
    delegate_to: localhost

#  - role: calico
#    delegate_to: localhost

  - role: k8s-resource
    k8s_resource_kind: Deployment
    k8s_resource_name: kubernetes-dashboard
    k8s_resource_namespace: kube-system
    k8s_resource_file: https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
    delegate_to: localhost

  - role: k8s-application
    app_name: nginx-ingress
    delegate_to: localhost

  - role: k8s-application
    app_name: kube-lego
    delegate_to: localhost

  - role: k8s-application
    app_name: mattermost
    delegate_to: localhost

  tasks:
  - include_role:
      name: k8s-application
    vars:
      app_name: youtrack
      youtrack_name: "{{ yt_item.name }}"
      youtrack_host: "{{ yt_item.host }}"
      k8s_application_target: "{{ inventory_dir }}/{{ kube_cluster_name }}-{{ app_name }}-{{ yt_item.name }}"
    with_items: "{{ youtrack_instances }}"
    loop_control:
      loop_var: yt_item
    delegate_to: localhost
