---

- name: Ensure target folder
  file:
    path: "{{ inventory_dir }}/{{ kube_cluster_name }}-nginx-ingress"
    state: directory

- name: Copy templates
  template:
    src: "{{ item }}"
    dest: "{{ inventory_dir }}/{{ kube_cluster_name }}-nginx-ingress/{{ item | basename }}"
  with_items:
  - 'templates/nginx-ingress/00-namespace.yaml'
  - 'templates/nginx-ingress/configmap.yaml'
  - 'templates/nginx-ingress/default-deployment.yaml'
  - 'templates/nginx-ingress/default-service.yaml'
  - 'templates/nginx-ingress/daemonset.yaml'

- name: Create namespace
  include_role:
    name: k8s-resource
  vars:
    k8s_resource_kind: namespace
    k8s_resource_name: nginx-ingress
    k8s_resource_namespace: nginx-ingress
    k8s_resource_file: '{{ inventory_dir }}/{{ kube_cluster_name }}-nginx-ingress/00-namespace.yaml'

- name: Create configmap
  include_role:
    name: k8s-resource
  vars:
    k8s_resource_kind: configmap
    k8s_resource_name: nginx
    k8s_resource_namespace: nginx-ingress
    k8s_resource_file: '{{ inventory_dir }}/{{ kube_cluster_name }}-nginx-ingress/configmap.yaml'

- name: Create default deployment
  include_role:
    name: k8s-resource
  vars:
    k8s_resource_kind: deployment
    k8s_resource_name: default-http-backend
    k8s_resource_namespace: nginx-ingress
    k8s_resource_file: '{{ inventory_dir }}/{{ kube_cluster_name }}-nginx-ingress/default-deployment.yaml'

- name: Create default service
  include_role:
    name: k8s-resource
  vars:
    k8s_resource_kind: service
    k8s_resource_name: default-http-backend
    k8s_resource_namespace: nginx-ingress
    k8s_resource_file: '{{ inventory_dir }}/{{ kube_cluster_name }}-nginx-ingress/default-service.yaml'

- name: Create daemonset
  include_role:
    name: k8s-resource
  vars:
    k8s_resource_kind: daemonset
    k8s_resource_name: nginx
    k8s_resource_namespace: nginx-ingress
    k8s_resource_file: '{{ inventory_dir }}/{{ kube_cluster_name }}-nginx-ingress/daemonset.yaml'
