apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: youtrack-{{ app_id }}
  namespace: youtrack
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: youtrack-{{ app_id }}
        app: youtrack
    spec:
      containers:
      - name: youtrack-{{ app_id }}
        image: uniplug/youtrack
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - mountPath: /opt/youtrack/data
          name: data
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 300
      volumes:
      - name: data
        hostPath:
          path: /data/youtrack/{{ app_id }}
